//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactGroupDef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContactGroupDef()
        {
            this.ContactGroup = new HashSet<ContactGroup>();
        }
    
        public long Id { get; set; }
        public string GroupName { get; set; }
        public long GroupType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactGroup> ContactGroup { get; set; }
    }
}
